name: Build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Get Vars
        run: |
          echo $BRANCH_NAME
          env
