name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
    

env:
  MAIN_BRANCH: main
  NAME_PROD: production
  NAME_DEV: develop    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: | 
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "NAME=${{ fromJSON('["$NAME_DEV", "$NAME_PROD"]')[github.ref == 'refs/heads/main'] }}" >> $GITHUB_ENV
          echo "NAME2=$([ ${GITHUB_REF##*/} == $MAIN_BRANCH ] && echo $NAME_PROD || echo $NAME_DEV)" >> $GITHUB_ENV
      
      - name: Get Vars
        run: |
          echo $BRANCH_NAME
          echo $NAME
          echo $NAME2
          env

