name: deploy-promotion

on:
  push:
    branches: [ main ]

env:
  ENV_NAME_DEV: develop
  ENV_NAME_PROD: production
  SLACK_CHANNEL_DEV: develop
  SLACK_CHANNEL_PROD: production

jobs:
  # pre-deploy build & unit tests
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building..."

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "unit testing..."

  # develop environment deploy & test
  deploy-develop:
    runs-on: ubuntu-latest
    environment: develop
    needs: unit-test
    steps:
      - run: echo "deploying to develop..."

  integration-test-develop:
    runs-on: ubuntu-latest
    needs: deploy-develop
    steps:
      - run: echo "integration testing..."

  user-acceptance-test:
    runs-on: ubuntu-latest
    needs: deploy-develop
    steps:
      - run: echo "user acceptance testing..."

  # production environment deploy & test
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: [ integration-test-develop, user-acceptance-test ]
    steps:
      - run: echo "deploying to production"

  integration-test-production:
    runs-on: ubuntu-latest
    environment: deploy-production
    needs: integration-test
    steps:
      - run: echo "integration testing production..."