name: deploy-promotion

on:
  push:
    branches: [ main ]

env:
  ENV_NAME_DEV: develop
  ENV_NAME_PROD: production
  SLACK_CHANNEL_DEV: develop
  SLACK_CHANNEL_PROD: production

jobs:
  # pre-deploy build & unit tests
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building..."

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "unit testing..."

  # develop environment deploy & test
  deploy-develop:
    runs-on: ubuntu-latest
    environment:
      name: develop
      url: https://dev.example.com
    needs: unit-test
    steps:
      - run: echo "deploying to develop..."

  integration-test-develop:
    runs-on: ubuntu-latest
    needs: deploy-develop
    steps:
      - run: echo "integration testing..."

  visual-test-develop:
    runs-on: ubuntu-latest
    needs: deploy-develop
    steps:
      - run: echo "visual testing..."

  # production environment deploy & test
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    needs: [ integration-test-develop, visual-test-develop ]
    steps:
      - run: echo "deploying to production"

  integration-test-production:
    runs-on: ubuntu-latest
    needs: deploy-production
    steps:
      - run: echo "integration testing production..."

  visual-test-production:
    runs-on: ubuntu-latest
    needs: deploy-develop
    steps:
      - run: echo "visual testing..."