name: deploy-promotion

on:
  push:
    branches: [ main ]

env:
  ENV_NAME_DEV: develop
  ENV_NAME_PROD: production
  SLACK_CHANNEL_DEV: develop
  SLACK_CHANNEL_PROD: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  develop:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - uses: actions/checkout@v2

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: develop

    steps:
      - uses: actions/checkout@v2